In [3]:
import numpy as np

# Creating a 1D array
array = np.arange(1, 13)  # Array of numbers from 1 to 12

# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(4, 3)
print("Reshaped to 4x3:\n", reshaped_array)

# Reshaping to a 2x6 matrix
reshaped_array2 = array.reshape(2, 6)
print("Reshaped to 2x6:\n", reshaped_array2)


Reshaped to 4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaped to 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [4]:
transposed_array = reshaped_array2.T
print("Transposed array:\n", transposed_array)

Transposed array:
 [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [10]:
# Creating a 1D array
array = np.arange(1, 13)  # Array of numbers from 1 to 12

# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(4, 3)
print("Reshaped to 4x3:\n", reshaped_array)

transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

#reshape to 1D
reshaped_array2 = transposed_array.reshape(1, 12)
print("Reshaped to 1D:\n", reshaped_array2)


Reshaped to 4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transposed array:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Reshaped to 1D:
 [[ 1  4  7 10  2  5  8 11  3  6  9 12]]


In [11]:
# Define two matrices
matrix_B = np.array([[1, 2, 3], [4, 5, 6]])
matrix_C = np.array([[1, 1, 1], [1, 1, 1]])

# Adding and subtracting matrices
sum_matrix = np.add(matrix_B, matrix_C)
diff_matrix = np.subtract(matrix_B, matrix_C)

print("Sum of Matrices:\n", sum_matrix)
print("Difference of Matrices:\n", diff_matrix)

Sum of Matrices:
 [[2 3 4]
 [5 6 7]]
Difference of Matrices:
 [[0 1 2]
 [3 4 5]]
