In [1]:
import numpy as np

In [2]:
temp = np.array([25,18,19,17,24,18,20])
print('The tempreture of this week are:',temp)

The tempreture of this week are: [25 18 19 17 24 18 20]


In [5]:
rand_2d = np.array([[1,7,3,2,4],[3,8,1,7,3]])
print('Random 2d array:',rand_2d)
print('Shape:',rand_2d.shape)

Random 2d array: [[1 7 3 2 4]
 [3 8 1 7 3]]
Shape: (2, 5)


In [6]:
img = [[[100,123,456],
        [100,123,456],
        [100,123,456],
          [100,123,456],
          [100,123,456],
          [100,123,456],
            [100,123,456],
            [100,123,456],
            [100,123,456]]]
print

[[[100, 123, 456], [100, 123, 456], [100, 123, 456], [100, 123, 456], [100, 123, 456], [100, 123, 456], [100, 123, 456], [100, 123, 456], [100, 123, 456]]]


In [18]:
arr = np.arange(1,11)
arr[4] = 50 #cgange the 3rd element
print(arr)


[ 1  2  3  4 50  6  7  8  9 10]


In [ ]:
arr[3,8] = arr[3,8 ]* -1

In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
for i in arr:
  arr[3:7] = i * -1
print(arr)


[  1   2   3 -10 -10 -10 -10   8   9  10]


In [14]:
import random
arr = np.random.randint(1, 100, 20)
print(arr)
arr[arr > 50] = -1
print(arr)

[47  1 58 59  7 20 67 32 15 28 38 12 50 48 97 29 43 58 73 71]
[47  1 -1 -1  7 20 -1 32 15 28 38 12 50 48 -1 29 43 -1 -1 -1]


In [20]:
two = np.arange(25).reshape((5,5))
two

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
two[[np.arange(5)],[np.arange(5)]] = two[[np.arange(5)],[np.arange(5)]]*2
two

array([[ 0,  1,  2,  3,  4],
       [ 5, 24,  7,  8,  9],
       [10, 11, 48, 13, 14],
       [15, 16, 17, 72, 19],
       [20, 21, 22, 23, 96]])

In [24]:
origin = np.arange(10)
origin

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
slic = origin[2:5]
slic[0] =99
print(origin)
print(slic)

[ 0  1 99  3  4  5  6  7  8  9]
[99  3  4]
