In [1]:
import numpy as np

Ex. 1

In [2]:
array_1d = np.arange(10)
print("1D Array:", array_1d)

1D Array: [0 1 2 3 4 5 6 7 8 9]


Ex.2

In [3]:
original_list = [3.14, 2.17, 0, 1, 2]
numpy_array = np.array(original_list)
integer_array = numpy_array.astype(int)

print(integer_array)

[3 2 0 1 2]


Ex.3

In [4]:
values = np.arange(1,10)
array_3_3 = values.reshape(3,3)

print(array_3_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Ex.4

In [5]:
random_array = np.random.rand(4,5)

print(random_array)

[[0.4714784  0.02862064 0.33893809 0.80138207 0.88982023]
 [0.5850972  0.1888115  0.08597239 0.64014354 0.86940235]
 [0.14857267 0.75205652 0.52927557 0.9790627  0.51390165]
 [0.06789839 0.24127239 0.13507406 0.5626258  0.52564235]]


Ex.5

In [7]:
array_2d = np.array([[1, 2, 3, 4, 5], [20, 21, 22, 23, 24], [40, 41, 42, 43, 44]])
second_row = array_2d[1]

print(second_row)

[20 21 22 23 24]


Ex.6

In [10]:
array1 = np.arange(10)
reversed_array = array1[::-1]

print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


Ex.7

In [11]:
identity_matrix = np.identity(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Ex.8

In [15]:
a = np.array([1, 2, 3, 4, 5])

print(f'"Sum:" {np.sum(a)}, "Average:" {np.mean(a)}')

"Sum:" 15, "Average:" 3.0


Ex.9

In [18]:
array = np.arange(1, 21)
reshaped_array = array.reshape(4, 5)

print(reshaped_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Ex.10

In [19]:
nums = np.arange(10)
odd_numbers = nums[nums % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]
